#include "rb.h"

int main()
{
	RB_tree *tt = rb_create(comparison_s, free_key, free_data);
	char *s1 = (char *)malloc(sizeof(char) * 6);
	strcpy(s1, "CABCD");
	char *s1_d = (char *)malloc(sizeof(char) * 6);
	strcpy(s1_d, "CABCD");
	char *s2 = (char *)malloc(sizeof(char) * 6);
	strcpy(s2, "EABCD");
	char *s2_d = (char *)malloc(sizeof(char) * 6);
	strcpy(s2_d, "EABCD");
	char *s3 = (char *)malloc(sizeof(char) * 6);
	strcpy(s3, "SABCD");
	char *s3_d = (char *)malloc(sizeof(char) * 6);
	strcpy(s3_d, "SABCD");
	char *s4 = (char *)malloc(sizeof(char) * 6);
	strcpy(s4, "AABCD");
	char *s4_d = (char *)malloc(sizeof(char) * 6);
	strcpy(s4_d, "AABCD");
	char *s5 = (char *)malloc(sizeof(char) * 6);
	strcpy(s5, "RABCD");
	char *s5_d = (char *)malloc(sizeof(char) * 6);
	strcpy(s5_d, "RABCD");
	char *s6 = (char *)malloc(sizeof(char) * 6);
	strcpy(s6, "HABCD");
	char *s6_d = (char *)malloc(sizeof(char) * 6);
	strcpy(s6_d, "HABCD");
	char *s7 = (char *)malloc(sizeof(char) * 6);
	strcpy(s7, "MABCD");
	char *s7_d = (char *)malloc(sizeof(char) * 6);
	strcpy(s7_d, "MABCD");
	char *s8 = (char *)malloc(sizeof(char) * 6);
	strcpy(s8, "PABCD");
	char *s8_d = (char *)malloc(sizeof(char) * 6);
	strcpy(s8_d, "PABCD");
	char *s9 = (char *)malloc(sizeof(char) * 6);
	strcpy(s9, "FABCD");
	char *s9_d = (char *)malloc(sizeof(char) * 6);
	strcpy(s9_d, "FABCD");
	char *s10 = (char *)malloc(sizeof(char) * 6);
	strcpy(s10, "NABCD");
	char *s10_d = (char *)malloc(sizeof(char) * 6);
	strcpy(s10_d, "NABCD");
	char *s11 = (char *)malloc(sizeof(char) * 6);
	strcpy(s11, "TABCD");
	char *s11_d = (char *)malloc(sizeof(char) * 6);
	strcpy(s11_d, "TABCD");
	// CESARHMPFNT
	// RB_tree *tt = rb_create(comparison_s, NULL, NULL);
	// char *s1 = "C";
	// char *s1_d = "C";
	// char *s2 = "E";
	// char *s2_d = "E";
	// char *s3 = "S";
	// char *s3_d = "S";
	// char *s4 = "A";
	// char *s4_d = "A";
	// char *s5 = "R";
	// char *s5_d = "R";
	// char *s6 = "H";
	// char *s6_d = "H";
	// char *s7 = "M";
	// char *s7_d = "M";
	// char *s8 = "P";
	// char *s8_d = "P";
	// char *s9 = "F";
	// char *s9_d = "F";
	// char *s10 = "N";
	// char *s10_d = "N";
	// char *s11 = "T";
	// char *s11_d = "T";
	rb_insert(tt, s1, s1_d);
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_insert(tt, s2, s2_d);
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_insert(tt, s3, s3_d);
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_insert(tt, s4, s4_d);
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_insert(tt, s5, s5_d);
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_insert(tt, s6, s6_d);
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_insert(tt, s7, s7_d);
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_insert(tt, s8, s8_d);
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_insert(tt, s9, s9_d);
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_insert(tt, s10, s10_d);
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_insert(tt, s11, s11_d);
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_remove(tt,(void*)"RABCD");
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_remove(tt,(void*)"EABCD");
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_remove(tt,(void*)"MABCD");
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_remove(tt,(void*)"NABCD");
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_remove(tt,(void*)"SABCD");
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_remove(tt,(void*)"PABCD");
	rb_print(tt, 6);
	rb_print(tt, 5);
	rb_remove_tree(tt);
	printf("%p\n", tt);
	if (!tt->root) printf("done.\n");
	rb_print(tt, 6);
	rb_print(tt, 5);
	free(tt);
	tt = NULL;
//	rb_remove(tt,(void*)"C");
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove(tt,(void*)"H");
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove(tt,(void*)"T");
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove(tt,(void*)"A");
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	free(tt);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
	

	return 0;
}
