#include "rb.h"

int main()
{
	// CESARHMHPFNT
	RB_tree *tt = rb_create(comparison_s, NULL, NULL);
	char *s1 = "C";
	char *s1_d = "C";
	char *s2 = "E";
	char *s2_d = "E";
	char *s3 = "S";
	char *s3_d = "S";
	char *s4 = "A";
	char *s4_d = "A";
	char *s5 = "R";
	char *s5_d = "R";
	char *s6 = "H";
	char *s6_d = "H";
	char *s7 = "M";
	char *s7_d = "M";
	char *s8 = "P";
	char *s8_d = "P";
	char *s9 = "F";
	char *s9_d = "F";
	char *s10 = "N";
	char *s10_d = "N";
	char *s11 = "T";
	char *s11_d = "T";
	rb_insert(tt, s1, s1_d);
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_insert(tt, s2, s2_d);
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_insert(tt, s3, s3_d);
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_insert(tt, s4, s4_d);
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_insert(tt, s5, s5_d);
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_insert(tt, s6, s6_d);
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_insert(tt, s7, s7_d);
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_insert(tt, s8, s8_d);
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_insert(tt, s9, s9_d);
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_insert(tt, s10, s10_d);
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_insert(tt, s11, s11_d);
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_remove(tt,(void*)"R");
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_remove(tt,(void*)"E");
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_remove(tt,(void*)"M");
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_remove(tt,(void*)"N");
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_remove(tt,(void*)"S");
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_remove(tt,(void*)"P");
	rb_print(tt, 1);
	rb_print(tt, 5);
	rb_remove_tree(tt);
	printf("%p\n", tt);
	if (!tt->root) printf("done.\n");
	rb_print(tt, 1);
	rb_print(tt, 5);
	free(tt);
	tt = NULL;
//	rb_remove(tt,(void*)"C");
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove(tt,(void*)"H");
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove(tt,(void*)"T");
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove(tt,(void*)"A");
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	free(tt);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
//	rb_remove_min(tt);
//	rb_print(tt, 1);
//	rb_print(tt, 5);
	

	return 0;
}
